### PR TITLE
Changed to scigraph loader for GO

### PR DESCRIPTION
**Pull request by cmungall**
Added GO noctua models (these will not be visible in the monarch app). See https://github.com/geneontology/go-site/issues/169

Also added categories for GO roots

### CODE REVIEW

**Comment by jnguyenx** [comment]
@cmungall I'm getting parse exception from the owlapi, can you please check if this ontology file is valid?

```
WARNING: Failed to load ontology: http://build.berkeleybop.org/job/build-combined-noctua-models/lastSuccessfulBuild/artifact/noctua-models.owl
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing http://build.berkeleybop.org/job/build-combined-noctua-models/lastSuccessfulBuild/artifact/noctua-models.owl
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) KRSS2OWLParser
6) ManchesterOWLSyntaxOntologyParser
7) OWLOBO12Parser


Detailed logs:
--------------------------------------------------------------------------------
Parser: RDFXMLParser
org.xml.sax.SAXParseException; systemId: http://build.berkeleybop.org/job/build-combined-noctua-models/lastSuccessfulBuild/artifact/noctua-models.owl; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

--------------------------------------------------------------------------------
Parser: OWLXMLParser
org.xml.sax.SAXParseException; systemId: http://build.berkeleybop.org/job/build-combined-noctua-models/lastSuccessfulBuild/artifact/noctua-models.owl; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

--------------------------------------------------------------------------------
Parser: OWLFunctionalSyntaxOWLParser
Encountered " "@" "@ "" at line 1, column 1.
Was expecting:
    "Ontology" ...
     (Line 0)

--------------------------------------------------------------------------------
Parser: TurtleOntologyParser
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered " <ERROR> "< "" at line 12462, column 3.
Was expecting:
    "]" ...


--------------------------------------------------------------------------------
Parser: KRSS2OWLParser
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered " <ERROR> "@ "" at line 1, column 1.
Was expecting:
    <EOF> 


--------------------------------------------------------------------------------
Parser: ManchesterOWLSyntaxOntologyParser
Encountered '@prefix : <http://model.geneontology.org/noctua-models.owl#> .' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)

--------------------------------------------------------------------------------
Parser: OWLOBO12Parser
org.coode.owlapi.obo12.parser.TokenMgrError: Lexical error at line 10, column 51.  Encountered: "\n" (10), after : ""


    at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:242)
    at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:867)
    at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:778)
    at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:735)
    at io.scigraph.owlapi.OwlApiUtils.loadOntology(OwlApiUtils.java:161)
    at io.scigraph.owlapi.loader.OwlOntologyProducer.call(OwlOntologyProducer.java:154)
    at io.scigraph.owlapi.loader.OwlOntologyProducer.call(OwlOntologyProducer.java:45)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by balhoff** [comment]
@jnguyenx I was able to load that file in Protege. It took a while but it looks fine.

**Comment by jnguyenx** [comment]
Thanks for checking.

If I wget the file and load it locally, it works fine. However it fails
when I try to use the remote one... any ideas?

**Comment by kltm** [comment]
@DoctorBud Ran into this recently elsewhere, but I'm forgetting where. IIRC, from another time this was cropping up, something about redirects triggers the parser to treat OWL files like OBO ones. @cmungall may have a better memory for where these tracker issues are.

**Comment by balhoff** [comment]
Same old problem as this? https://github.com/obophenotype/human-phenotype-ontology/issues/742

**Comment by DoctorBud** [comment]
When I download http://purl.obolibrary.org/obo/hp.owl to my machine, and then run owltools on it to generate a catalog and cache directory, it works fine. But when I tell owltools to load the http://purl.obolibrary.org/obo/hp.owl file from the web, I get the same error as above:

```
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
...
```

I don't think it's a download issue in terms of timeout, but it might be a character set issue (e.g., UTF-8 vs UTF-16) where the bytes that are obtained via owltools/owlapi are not the same bytes obtained via a prior curl/wget. I haven't studied this further; I just adapted my scripts to download hp.owl first.

**Comment by cmungall** [comment]
I believe we determined this was a timeout issue, hp.owl is large. But 
we need to investigate further, and push a fix to either the owlapi 
level or some wrapper level.

Is there a way to tell if gzip on the fly is being used?

**Comment by jnguyenx** [comment]
The owlapi opens a stream to the owl file then reads from there. No options can be set for gzip header as far as I can tell.

In that particular ontology there's a big import (owl:imports http://purl.obolibrary.org/obo/go/extensions/go-lego.owl), which causes nginx to time out and write some html code 504 error.

A fix is to increase the nginx timeout, I copied the file to the monarch-ttl server and it loads fine. We went with removing the big import, as it is not needed for now.

Thanks for the help!

**Pull request merged**
